language: php
php:
  - '5.6'
  - '7.0'
  - hhvm
  - 'nightly'

services:
  - mysql

matrix:
  allow_failures:
    - php: 'nightly'

before_script:
  - mysql < scripts/test_mysql.sql

install:
  - composer self-update
  - composer install --dev

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c tests/phpunit.xml

after_success:
  - travis_retry php vendor/bin/coveralls -v
  - travis_retry php vendor/bin/codacycoverage clover build/logs/clover.xml

cache:
  directories:
    - $HOME/.composer/cache

env:
  matrix:
    secure: EbLv/7qCnnZhHq7HRq+sDMWPxy6hiZs6DMZc8k7MARxMAiRihIieI4bKSe+1hPWxoegUtYnrWOQNzUhNkmfz5moXMGsrdGFgFflkR5AoqR9MjZQ7gJrN5AykdW6zQXvF4qsLxuvLh19sGA/NEXfaLx0Fj5N0LgDDk4q4/uCO528iUnG7r/YRpzY4S2ul7KSwvN1G6MYPcoN+77LCMTyMDicD2bFwv4htqrP445/wk9TqQ58sgFV09NNXs5BiJ1z4v14tiL88zrill1cp9sMsHAndGiVDQPz4p5bJmEepq1tsNq1UvJl1tpyBfswgk/I+CHyJiUJHI1dOazfSMDRPmGcmRUnRzKWNRm3Od4kwEJtEc7kVlfPBMU4UAQfX7Ghxnnj2xhJtrWZHohmKGm4qKRIu29+mk052DX9A47LfO6pQvpkREcq+vKq7Qd+dZfmnYNsVY/P0elunPMDllorm/i7Ot9ne3xtc1uE8CDZDF/OuQ1VxgJGC1CpstaIDQ2K1sulL7tQYjb70EKK/yPx/0/JzH2HQy8b8mIFzh897hJkAa5nPZMmIGTzyrCmkX9zKhSF6OreUWTV6JcB3zWXf9Yx3yPVAqSbdaIO3eRJzyc11/3YnA1e+sltvuwIviXLMwgDd1+gWlWd1Fhdeq4C4RPdat29w5t+39Fq8N4xAD1Q=

notifications:
  webhooks:
    - https://buildtimetrend.herokuapp.com/travis