language: php
php:
  - '5.6'
  - '7.0'
  - hhvm
  - 'nightly'

services:
  - mysql

matrix:
  allow_failures:
    - php: 'nightly'

before_script:
  - mysql < scripts/testing_mysql.sql

install:
  - composer self-update
  - composer install --dev

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c tests/phpunit.xml

after_success:
  - travis_retry php vendor/bin/coveralls -v

cache:
  directories:
    - $HOME/.composer/cache